CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS REQUESTS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL,
    REQUESTER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    IS_AVIALABLE BOOLEAN NOT NULL,
    OWNER_ID INTEGER REFERENCES USERS(ID),
    REQUEST_ID INTEGER REFERENCES REQUESTS(ID)
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    ITEM_ID INTEGER NOT NULL REFERENCES ITEMS(ID),
    BOOKER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    STATUS VARCHAR(50) CHECK(STATUS IN ('WAITING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS COMMENTS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXT VARCHAR(50) NOT NULL,
    ITEM_ID INTEGER NOT NULL REFERENCES ITEMS(ID),
    AUTHOR_ID INTEGER NOT NULL REFERENCES USERS(ID),
    CREATED TIMESTAMP DEFAULT NOW()
);

